export const FETCH_LATEST_INCIDENT_STARTED = 'FETCH_LATEST_INCIDENT_STARTED';
export const INCIDENT_FETCH_SUCCEEDED = 'INCIDENT_FETCH_SUCCEEDED';
export const URL_INCIDENT_TABLE =
  'api/now/table/incident?sysparm_display_value=true';
export const DROPDOWN_PANEL_ITEM_CLICKED = 'NOW_DROPDOWN_PANEL#ITEM_CLICKED';
export const INCIDENT_DELETE_STARTED = 'INCIDENT_DELETE_STARTED';
export const URL_DELETE_INCIDENT = 'api/now/table/incident/:sys_id';
export const INCIDENT_CARD_OPENED = 'INCIDENT_CARD_OPENED';
export const INCIDENT_CARD_CLOSED = 'INCIDENT_CARD_CLOSED';
export const INCIDENT_DELETE_SUCCEEDED = 'INCIDENT_DELETE_SUCCEEDED';
export const MODAL_DELETE_BUTTON_CLICKED = 'NOW_MODAL#FOOTER_ACTION_CLICKED';
export const MODAL_DISMISSED = 'NOW_MODAL#OPENED_SET';

export const nowCardActionsId = {
  open: 'open',
  delete: 'delete',
};
